### ISSUE TITLE
Try, Except, Pass detected.

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/seagate-tools#484]
#### Occurred on:
+ **Commit**:  f3eec42ca01a90ba8ab2d50c01e8e3079f59a362
+ **File**:    [performance/PerfPro/callbacks/anstomlog.py](https://github.com/Seagate/seagate-tools/blob/f3eec42ca01a90ba8ab2d50c01e8e3079f59a362/performance/PerfPro/callbacks/anstomlog.py)
+ **LineNum**: [404](https://github.com/Seagate/seagate-tools/blob/f3eec42ca01a90ba8ab2d50c01e8e3079f59a362/performance/PerfPro/callbacks/anstomlog.py#L404)
+ **Code**:    `except:`

    
#### Currently on:
+ **Commit**:  8cb5c624d5223f1adadc936267c5b99613c1073f
+ **File**:    [performance/PerfPro/callbacks/anstomlog.py](https://github.com/Seagate/seagate-tools/blob/8cb5c624d5223f1adadc936267c5b99613c1073f/performance/PerfPro/callbacks/anstomlog.py)
+ **LineNum**: [404](https://github.com/Seagate/seagate-tools/blob/8cb5c624d5223f1adadc936267c5b99613c1073f/performance/PerfPro/callbacks/anstomlog.py#L404)

**Comment by sampadap03** [comment]
files are removed from the directory
