### ISSUE TITLE
Disable camel case pattern completely from seagate-tools repo

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/seagate-tools#537]
#### Occurred on:
+ **Commit**:  6d280174c61568680d5cb9995884a0ad19917664
+ **File**:    [performance/PerfLine/roles/perfline_setup/files/webui/templates/scripts/compare_runs.js](https://github.com/Seagate/seagate-tools/blob/6d280174c61568680d5cb9995884a0ad19917664/performance/PerfLine/roles/perfline_setup/files/webui/templates/scripts/compare_runs.js)
+ **LineNum**: [36](https://github.com/Seagate/seagate-tools/blob/6d280174c61568680d5cb9995884a0ad19917664/performance/PerfLine/roles/perfline_setup/files/webui/templates/scripts/compare_runs.js#L36)
+ **Code**:    `if (isNaN(base_val) || isNaN(value) || base_val === null || value === null)`

    
#### Currently on:
+ **Commit**:  39f69184d9c61335f738434ebe7658eae221ae99
+ **File**:    [performance/PerfLine/roles/perfline_setup/files/webui/templates/scripts/compare_runs.js](https://github.com/Seagate/seagate-tools/blob/39f69184d9c61335f738434ebe7658eae221ae99/performance/PerfLine/roles/perfline_setup/files/webui/templates/scripts/compare_runs.js)
+ **LineNum**: [56](https://github.com/Seagate/seagate-tools/blob/39f69184d9c61335f738434ebe7658eae221ae99/performance/PerfLine/roles/perfline_setup/files/webui/templates/scripts/compare_runs.js#L56)

**Comment by sampadap03** [comment]
closing as mentioned^

**Comment by cortx-admin** [comment]
> Sampada Petkar commented in Jira Server:

closing as pattern is disabled by Rahul Kumar earlier

**Comment by cortx-admin** [comment]
> Sampada Petkar commented in Jira Server:

^

**Comment by cortx-admin** [comment]
> Sampada Petkar commented in Jira Server:

^
